version: 0.2
env:
  exported-variables:
    - CODEBUILD_BUILD_NUMBER
    - commit_number
phases:
  build:
    commands:
      - source=CODEBUILD_SRC_DIR_${SystemComponent}_1_1
      - cd ${!source}
      - ls
      - cd aac
      - commit_number=$(git rev-parse HEAD | head -c7)
      - branch_name_with_slash=$(git rev-parse --abbrev-ref HEAD)
      - echo $branch_name_with_slash
      - branch_name=$(echo $branch_name_with_slash | sed "s~/~-~g")
      - repo_name=$(basename `git config --get remote.origin.url`)
      - sed -i "s/repo_name/$repo_name/g" src/index.html
      - sed -i "s~branch_name~$branch_name~g" src/index.html
      - sed -i "s/commit_number/$commit_number, build $CODEBUILD_BUILD_NUMBER, pipelineXID $PipelineExecutionId /g" src/index.html
      - echo n | npm install -g @angular/cli --silent
      - echo n | npm install --silent
      - ng analytics off
      - ng config -g cli.warnings.versionMismatch false
      - ng build
      - cp Dockerfile dist/my-app/Dockerfile
      - cp httprewrite.conf.template dist/my-app/httprewrite.conf.template
      - echo "commit_number=$commit_number" >> source-info.yaml
      - echo "branch_name=$branch_name" >> source-info.yaml
      - echo "repo_name=$repo_name" >> source-info.yaml
      - echo "build_number=$CODEBUILD_BUILD_NUMBER" >> source-info.yaml
      - cat source-info.yaml
      - cp source-info.yaml dist/my-app/source-info.yaml                
      - cd dist/my-app
      - zip -r $temp_storage_filename .
      - aws s3 cp $temp_storage_filename s3://$temp_storage_location/$temp_storage_subdirectory/$temp_storage_filename
